### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by zhutoujiang** [ShanghaiWuDun/rust-nasl#1]
Traceback (most recent call last):
  File "build.py", line 218, in <module>
    main()
  File "build.py", line 206, in main
    build()
  File "build.py", line 72, in build
    build_grammar()
  File "build.py", line 53, in build_grammar
    need_update = os.path.getmtime("./nasl/nasl_grammar.y") > os.path.getmtime("./nasl/nasl_grammar.tab.c") \
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: './nasl/nasl_grammar.tab.c'

**Comment by LuoZijun** [comment]
可以检查下你的工作目录，切换到 `./c/` .

**Comment by zhutoujiang** [comment]
工作目录就是在./c/，这个目录下面的nasl目录里面，并没有nasl_grammar.tab.c；nasl_grammar.tab.h；nasl_grammar.output；这三个文件

**Comment by LuoZijun** [comment]
因为 他是自动生成的: https://github.com/ShanghaiWuDun/rust-nasl/blob/master/c/build.py#L62

**Comment by LuoZijun** [comment]
我大概明白了，前面有判断了下。

**Comment by LuoZijun** [comment]
@zhutoujiang 刚更新了下，应该不会出现这个问题了。
