### ISSUE TITLE
build failure2

### ISSUE THREAD

**Issue by zhutoujiang** [ShanghaiWuDun/rust-nasl#2]
Traceback (most recent call last):
  File "build.py", line 222, in <module>
    main()
  File "build.py", line 210, in main
    build()
  File "build.py", line 107, in build
    need_update = os.path.getmtime(filename) > os.path.getmtime(objectname)
  File "/usr/local/var/pyenv/versions/3.5.0/lib/python3.5/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
FileNotFoundError: [Errno 2] No such file or directory: 'base/nvti.o'

**Comment by zhutoujiang** [comment]
逻辑可能有一点问题，base目录和util目录的.o文件都先调用了

**Comment by LuoZijun** [comment]
已更新。
